[package]
name = "music-tag-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
id3 = "1.6.0"
pest = "2.5.6"
pest_derive = "2.5.6"
